"""
FastAPI Microservice Template

A production-ready FastAPI microservice template with:
- RESTful API structure
- Database integration (SQLAlchemy + Alembic)
- Authentication (JWT)
- Docker support
- Testing setup
- API documentation
"""
from resoftai.templates.base import Template, TemplateVariable, TemplateFile, TemplateCategory


def create_fastapi_microservice_template() -> Template:
    """Create FastAPI microservice template"""

    return Template(
        id="fastapi-microservice",
        name="FastAPI Microservice",
        description="Production-ready FastAPI microservice with database, auth, and Docker",
        category=TemplateCategory.MICROSERVICE,
        author="ResoftAI",
        version="1.0.0",
        variables=[
            TemplateVariable(
                name="service_name",
                description="Name of your microservice (e.g., user-service, payment-service)",
                required=True,
                type="string"
            ),
            TemplateVariable(
                name="project_name",
                description="Python package name (will be generated from service_name)",
                required=False,
                type="string"
            ),
            TemplateVariable(
                name="database",
                description="Database type",
                type="choice",
                choices=["postgresql", "mysql", "sqlite"],
                default="postgresql"
            ),
            TemplateVariable(
                name="include_auth",
                description="Include JWT authentication",
                type="boolean",
                default=True
            ),
            TemplateVariable(
                name="include_docker",
                description="Include Docker configuration",
                type="boolean",
                default=True
            ),
            TemplateVariable(
                name="include_tests",
                description="Include test setup",
                type="boolean",
                default=True
            ),
        ],
        files=[
            # Main application
            TemplateFile(
                path="{{project_name|snake_case}}/main.py",
                content='''"""
{{service_name}} - FastAPI Microservice

Auto-generated by ResoftAI Template System
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{{service_name}}",
    description="{{service_name}} Microservice API",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    """Health check endpoint"""
    return {
        "service": "{{service_name}}",
        "status": "healthy",
        "version": "1.0.0"
    }

@app.get("/health")
async def health_check():
    """Detailed health check"""
    return {
        "status": "healthy",
        "database": "connected",  # Check actual DB connection
        "cache": "connected"
    }
'''
            ),

            # Database models
            TemplateFile(
                path="{{project_name|snake_case}}/models/__init__.py",
                content='''"""Database models"""
from {{project_name|snake_case}}.models.base import Base

__all__ = ["Base"]
'''
            ),
            TemplateFile(
                path="{{project_name|snake_case}}/models/base.py",
                content='''"""Base model configuration"""
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
'''
            ),

            # Database configuration
            TemplateFile(
                path="{{project_name|snake_case}}/db.py",
                content='''"""Database configuration"""
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
import os

{% if database == "postgresql" %}
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+asyncpg://user:password@localhost/{{project_name|snake_case}}"
)
{% elif database == "mysql" %}
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "mysql+aiomysql://user:password@localhost/{{project_name|snake_case}}"
)
{% else %}
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "sqlite+aiosqlite:///./{{project_name|snake_case}}.db"
)
{% endif %}

engine = create_async_engine(DATABASE_URL, echo=True)
async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

async def get_db():
    """Get database session"""
    async with async_session() as session:
        yield session
'''
            ),

            # Requirements
            TemplateFile(
                path="requirements.txt",
                content='''fastapi==0.104.1
uvicorn[standard]==0.24.0
{% if database == "postgresql" %}
sqlalchemy[asyncio]==2.0.23
asyncpg==0.29.0
{% elif database == "mysql" %}
sqlalchemy[asyncio]==2.0.23
aiomysql==0.2.0
{% else %}
sqlalchemy[asyncio]==2.0.23
aiosqlite==0.19.0
{% endif %}
{% if include_auth %}
python-jose[cryptography]==3.3.0
passlib[bcrypt]==1.7.4
python-multipart==0.0.6
{% endif %}
alembic==1.12.1
pydantic==2.5.0
python-dotenv==1.0.0
'''
            ),

            # Docker configuration
            TemplateFile(
                path="Dockerfile",
                content='''FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "{{project_name|snake_case}}.main:app", "--host", "0.0.0.0", "--port", "8000"]
''',
                is_template=True
            ) if "{{include_docker}}" else None,

            TemplateFile(
                path="docker-compose.yml",
                content='''version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL={{database_url}}
    depends_on:
      - db
  {% if database == "postgresql" %}
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: {{project_name|snake_case}}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  {% elif database == "mysql" %}
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: {{project_name|snake_case}}
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  {% endif %}
''',
                is_template=True
            ) if "{{include_docker}}" else None,

            # README
            TemplateFile(
                path="README.md",
                content='''# {{service_name}}

FastAPI microservice generated by ResoftAI.

## Features

- ✅ FastAPI framework
- ✅ {{database|title}} database
{% if include_auth %}
- ✅ JWT authentication
{% endif %}
{% if include_docker %}
- ✅ Docker support
{% endif %}
- ✅ Alembic migrations
- ✅ Pydantic validation
{% if include_tests %}
- ✅ Test suite (pytest)
{% endif %}

## Setup

1. Install dependencies:
```bash
pip install -r requirements.txt
```

2. Set environment variables:
```bash
cp .env.example .env
# Edit .env with your configuration
```

3. Run database migrations:
```bash
alembic upgrade head
```

4. Start the server:
```bash
uvicorn {{project_name|snake_case}}.main:app --reload
```

{% if include_docker %}
## Docker

Build and run with Docker:
```bash
docker-compose up -d
```
{% endif %}

## API Documentation

Once running, visit:
- Swagger UI: http://localhost:8000/docs
- ReDoc: http://localhost:8000/redoc

## Testing

{% if include_tests %}
Run tests:
```bash
pytest
```
{% else %}
Add tests in `tests/` directory.
{% endif %}

## Project Structure

```
{{project_name|snake_case}}/
├── models/          # Database models
├── routers/         # API routes
├── services/        # Business logic
├── schemas/         # Pydantic schemas
└── main.py          # Application entry point
```

## License

MIT License
'''
            ),
        ],
        directories=[
            "{{project_name|snake_case}}",
            "{{project_name|snake_case}}/models",
            "{{project_name|snake_case}}/routers",
            "{{project_name|snake_case}}/services",
            "{{project_name|snake_case}}/schemas",
            "tests",
            "alembic",
            "alembic/versions",
        ],
        requirements={
            "python": ">=3.9"
        },
        dependencies=[
            "fastapi",
            "uvicorn",
            "sqlalchemy",
            "alembic"
        ],
        setup_commands=[
            "pip install -r requirements.txt",
            "cp .env.example .env",
            "alembic upgrade head",
        ],
        readme_content="See README.md in generated project",
        tags=["fastapi", "microservice", "api", "rest", "python"],
        icon=None,
        screenshot=None
    )
